# Power System Analysis: Load Flow Techniques

This Notebook is made by:<br> <br> <b> Anmol Tripathi </b>, <br> B.tech Electrical Engineering, <br>Institute of Technology, Nirma University,<br> Ahmedabad, India

## Load Flow: A power system snapshot analysis

...<br>....<br>....

### Load Flow 

<b> Introduction<br>
<del> Ybus Formation </del> <br>
DC Load Flow Analysis <br>
Gauss Itteratice Method <br>
Gauss Siedel Analysis <br>
Newton Raphson Method Polar<br>
Newton Raphson Method Rectangular<br>
Decoupled Method <br>
Fast Decoupled Method <br></b>

### Economic Load Dispatch

<b> Newton Raphson Method<br>
Advanced Methodologies<br></b>

# Contents

* [Introduction](#Introduction) <br>

* [Handling data](#Handling-data) <br>
> [Line and Bus Data](#Line-and-bus-data) <br>
>> [Entering the Line Data](#Entering-the-line-data) <br>
>> [Writing the line data to a CSV file](#Writing-the-line-data-to-a-CSV-file) <br>
>> [Reading the line data from a CSV file](#Reading-the-line-data-from-a-CSV-file) <br>

* [Y<sub>bus</sub> and Z<sub>bus</sub> Formation](#Ybus-formation) <br>
* [DC Loadflow Analysis](#DC-Load-Flow-Analysis) <br>

...<br>....<br>....

# Introduction

Assumptions made while performing load flow:
* Line Resistance being small, are neglected, i.e. Active power loss in the system is zero
* Considering stability, hence 
$\sin(\delta_i - \delta_k) \approx (\delta_i - \delta_k)$ (As, for small values of $\theta$, $\sin\theta \approx \theta$)

<br>...<br>....<br>....

In [1]:
import numpy as np
import os
import cmath
import csv
import pandas as pd
from tkinter import *

In [ ]:
# REMOVE IT


#Tkinter start basics
import tkinter.messagebox
def main():
    global entry1
    root = Tk()
    label1 = Label(text="Computer Techniques in Power System")
    label1.pack()

    entry1= Entry(bd=2)
    entry1.pack()

    button1 = Button(text="Welcome",command=hello)
    button1.pack()
    root.mainloop()

def hello():
    tkinter.messagebox.showinfo("GUI Program","Hello "+entry1.get())
    
if __name__=='__main__':
    main()

# Handling data

<br>...<br>....<br>.... About line and Bus data

## Line data

### Entering the line data

<br>...<br>....<br>....

In [ ]:
def enter_line_data():
    nb = int(input("Enter the number of Buses: ")) 
    nl = int(input("Enter the number of Lines: "))
    from_bus = []
    to_bus = []
    R = []
    X = []
    Z = []
    G = []
    B = []
    Y = []
    turns_ratio = []
    for i in range(0,nl):
        print("\n\n Entry Number: ", i+1)
        x = float(input("\n Enter the from bus: "))
        if(x<=nb):
            from_bus.append(x)
        x = float(input("\n Enter the to bus: "))
        if(x<=nb):
            to_bus.append(x)
        x = float(input("\n Enter the Line Resistance: "))
        R.append(x)
        x = float(input("\n Enter the Line Reactance: "))
        X.append(x)
        x = complex(R[i],X[i])
        g = complex("{0:.2f}".format(x))
        Z.append(g)
        print("\n Line Impedence = ", Z[i])

        Y.append(1/Z[i])
        G.append(Y[i].real)
        B.append(Y[i].imag)
        print("\n Line Admittance = ", Y[i])
        x = float(input("\n Enter the turns ratio: "))
        turns_ratio.append(x)
    data_matrix = [(from_bus[i], to_bus[i], R[i], X[i], Z[i], G[i], B[i], Y[i], turns_ratio[i]) for i in range(0, nl)] 
    data_matrix = pd.DataFrame(data_matrix, columns=['From_Bus','To_Bus','R','X','Z','G','B','Y','Turns_Ratio'])
    return data_matrix

In [ ]:
data_matrix = enter_line_data()

In [ ]:
data_matrix

### Writing the line data to a CSV file

<br>...<br>....<br>....

In [2]:
def line_write_to_csv(data_matrix):
    dir_path = os.getcwd()
    filename = input("Enter the Filename: ")
    filename = filename + '.csv'
    export_csv = data_matrix.to_csv (os.path.join(dir_path,filename), index = None, header=True)

In [3]:
line_write_to_csv(data_matrix)

NameError: name 'data_matrix' is not defined

### Reading the line data from a CSV file

<br>...<br>....<br>....

In [2]:
def line_read_from_csv():
    print("\n\n Please make sure that the CSV has data in following format: \n\n\n From Bus\tTo Bus\t R\tX\tZ\tG\tB\tY\tTurns Ratio\n \n\n Note: The csv file should be in the same directory")
    filename = input("\n Enter the CSV Filename:  ")
    filename = filename + '.csv'
    dir_path = os.getcwd()
    csv_path = os.path.join(dir_path, filename)
    data = pd.read_csv(csv_path)
    data.head()
    return(data)

In [39]:
data_matrix = line_read_from_csv()
print(type(data_matrix))
data_matrix



 Please make sure that the CSV has data in following format: 


 From Bus	To Bus	 R	X	Z	G	B	Y	Turns Ratio
 

 Note: The csv file should be in the same directory

 Enter the CSV Filename:  line_data
<class 'pandas.core.frame.DataFrame'>


From_Bus  To_Bus     R      X           Z         G         B  \
0       1.0     2.0  34.0  53.00    (34+53j)  0.008575 -0.013367   
1       2.0     3.0  45.0  34.00    (45+34j)  0.014146 -0.010688   
2       3.0     5.0  34.0  54.00    (34+54j)  0.008350 -0.013261   
3       4.0     5.0  43.0   0.54  (43+0.54j)  0.023252 -0.000292   
4       3.0     1.0  34.0  43.00    (34+43j)  0.011314 -0.014309   

                                              Y  Turns_Ratio  
0  (0.008575031525851198-0.013366960907944515j)         0.10  
1  (0.014146494812951901-0.010688462747563658j)         4.00  
2   (0.008349705304518664-0.01326129666011788j)        34.00  
3  (0.0232521469302083-0.00029200370563517403j)         0.40  
4  (0.011314475873544092-0.014309484193011647j)         0.54

## Bus Data

<br>...<br>....<br>....

### Reading the bus data from a CSV file

<br>...<br>....<br>....

In [12]:
def bus_read_from_csv():
    print("\n\n Please make sure that the CSV has data in following format: \n\n\n Bus Number\tBus Type\tPg\tPd\tQg\tQd\tV\tdelta\tQmin\tQmax\tVmin\tVmax\t \n\n Note: The csv file should be in the same directory")
    filename = input("\n Enter the CSV Filename:  ")
    filename = filename + '.csv'
    dir_path = os.getcwd()
    csv_path = os.path.join(dir_path, filename)
    data = pd.read_csv(csv_path)
    data.head()
    return(data)

In [13]:
bus_read_from_csv()



 Please make sure that the CSV has data in following format: 


 Bus Number	Bus Type	Pg	Pd	Qg	Qd	V	delta	Qmin	Qmax	Vmin	Vmax	 

 Note: The csv file should be in the same directory

 Enter the CSV Filename:  bus_data


Empty DataFrame
Columns: [Bus_no, Bus_type, Pg, Pd, Qg, Qd, V, delta, Qmin, Qmax, Vmin, Vmax]
Index: []

## Checking Matrix to be Symmetric

...<br>
,..

In [22]:
def check_symmetric(a, tol=1e-8):
    return np.all(np.abs(a-a.T) < tol)

True

# Bus Incidence Matrix 

...<br>
...<br>
...

In [72]:
def make_bus_incidence_matrix(datamatrix):
    linedata = datamatrix
    frombus = linedata.iloc[:,0].astype(int) #Because float isn't itteratable
    tobus = linedata.iloc[:,1].astype(int)
    no_bus = max(max(frombus),max(tobus)) #To find number of buses 
    bus_incidence = np.zeros((no_bus+1,no_bus+1)).astype(int)
    for i in range(0,no_bus):
        bus_incidence[frombus[i]][tobus[i]] = 1
    bus_incidence = np.delete(bus_incidence,0,0)
    bus_incidence = np.delete(bus_incidence,0,1)
    return bus_incidence

In [74]:
bus_incidence =  make_bus_incidence_matrix(data_matrix)
print(bus_incidence)

[[0 1 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [75]:
check_symmetric(bus_incidence)

False

# Y<sub>bus</sub> and Z<sub>bus</sub> Formation

<br>...<br>....<br>....<br>...<br>....<br>....

In [19]:
def make_ybus(datamatrix):
    linedata = datamatrix
    frombus = linedata.iloc[:,0].astype(int) #Because float isn't itteratable
    tobus = linedata.iloc[:,1].astype(int)
    no_bus = max(max(frombus),max(tobus)) #To find number of buses 
    y_bus = np.zeros((no_bus+1,no_bus+1)).astype(complex)
    for i in range(0,no_bus):
        y_bus[frombus[i],tobus[i]] = -(complex(linedata.iloc[i,7]))
        y_bus[tobus[i],frombus[i]] = -(complex(linedata.iloc[i,7]))
        y_bus[frombus[i],frombus[i]] = y_bus[frombus[i],frombus[i]] + (complex(linedata.iloc[i,7]))
        y_bus[tobus[i],tobus[i]] = y_bus[tobus[i],tobus[i]] + (complex(linedata.iloc[i,7]))
    y_bus = np.delete(y_bus,0,0)
    y_bus = np.delete(y_bus,0,1)
    print("Ybus Formed")
    return y_bus

In [20]:
ybus = make_ybus(data_matrix)

Ybus Formed


In [21]:
ybus

array([[ 0.01988951-0.02767645j, -0.00857503+0.01336696j,
        -0.01131448+0.01430948j,  0.        +0.j        ,
         0.        +0.j        ],
       [-0.00857503+0.01336696j,  0.02272153-0.02405542j,
        -0.01414649+0.01068846j,  0.        +0.j        ,
         0.        +0.j        ],
       [-0.01131448+0.01430948j, -0.01414649+0.01068846j,
         0.03381068-0.03825924j,  0.        +0.j        ,
        -0.00834971+0.0132613j ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.02325215-0.000292j  ,
        -0.02325215+0.000292j  ],
       [ 0.        +0.j        ,  0.        +0.j        ,
        -0.00834971+0.0132613j , -0.02325215+0.000292j  ,
         0.03160185-0.0135533j ]])

In [23]:
zbus = np.linalg.inv(ybus)
zbus

array([[9.43466932e+16-1.27761147e+16j, 9.43466932e+16-1.27761147e+16j,
        9.43466932e+16-1.27761147e+16j, 9.43466932e+16-1.27761147e+16j,
        9.43466932e+16-1.27761147e+16j],
       [9.43466932e+16-1.27761147e+16j, 9.43466932e+16-1.27761147e+16j,
        9.43466932e+16-1.27761147e+16j, 9.43466932e+16-1.27761147e+16j,
        9.43466932e+16-1.27761147e+16j],
       [9.43466932e+16-1.27761147e+16j, 9.43466932e+16-1.27761147e+16j,
        9.43466932e+16-1.27761147e+16j, 9.43466932e+16-1.27761147e+16j,
        9.43466932e+16-1.27761147e+16j],
       [9.43466932e+16-1.27761147e+16j, 9.43466932e+16-1.27761147e+16j,
        9.43466932e+16-1.27761147e+16j, 9.43466932e+16-1.27761147e+16j,
        9.43466932e+16-1.27761147e+16j],
       [9.43466932e+16-1.27761147e+16j, 9.43466932e+16-1.27761147e+16j,
        9.43466932e+16-1.27761147e+16j, 9.43466932e+16-1.27761147e+16j,
        9.43466932e+16-1.27761147e+16j]])

# Gauss Siedel Method

Gauss Siedel is an itterative algorithm for solving set of non-linear algebraic equations

As we know, <br>
<img src="images/Vi.jpg">
<br>
<img src="images/Gauss-Seidel-Method-Flowchart.jpg">

In [77]:
def Gauss_Siedel_Load_Flow(linedata,busdata,ittr_limit):
    ybus = make_ybus(linedata)
    Vinitial = cmath.polar(complex(1,0))
    tolerance = 0.0001
    ittr = 0
    busdata['V'] = np.where(busdata['Bus_type']=='PV',Vinitial)
    busdata['V'] = np.where(busdata['Bus_type']=='PQ',Vinitial)
#     A = complex(busdata['P'],busdata['Q'])
#     B = linedata['Y']/(np.diagonal['Y'])
    while((change_in_V > tolerance) and (ittr < ittr_limit)):
        for i in range(0,max(busdata['Bus_no'])):
            if(busdata[i]['Bus_type'] == 'PV'):
                busdata[i]['delta'] = math.degrees(math.atan( (busdata[i][V].imag) / (busdata[i][V].real)))
                busdata[i][V].imag = busdata[i][V].magnitude * sin(busdata[i]['delta'])
            ittr = ittr + 1

        

In [ ]:
Gauss_Siedel_Load_Flow(data_matrix)